version: '3'
services:
  portfolio:
    build: .
    image: portfolio
    container_name: portfolio
    ports:
      - 1997:3000
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
